### ISSUE TITLE
Superadmin

### ISSUE THREAD

**Issue by Shru95** [Prasad108/BDM_Client#13]
## SuperAdmin
- Create center and its admin
- Approve new book request
  - Add/modify book name
  - Add/modify language
  - Add/modify type

**Comment by Prasad108** [comment]
### For Admin we should create new Center 
- As per the current MySql schema every user must belong to some center (because of foreign key).
- So to avoid any confusion we should create a new center and put the Super-Admin over there 
  - this will resolve the problem that Super-Admin will be shown in the user list of some center.
